language: ruby
rvm:
  - 2.2.0
script:
  - bundle update && bundle install && bundle exec jekyll build --config _config.yml,_config_cit.yml && bundle exec htmlproof ./_site
branches:
  only:
    - master
