# Site settings
title: "Elmire & Romain"
url: "http://www.elmire-et-romain.fr"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog/
copyright_owner: Elmire Combescot & Romain Degoul

# Build settings:
markdown: kramdown
encoding: utf-8
timezone: Europe/Paris
sass:
  style: :compressed
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  profile: false
  ignore:
    envs: [development]  # Skips HTML compression if the following environment variable is set: JEKYLL_ENV=development
